### ISSUE TITLE
Happy Eyeballs between sctp and tcp doesn't work

### ISSUE THREAD

**Issue by adventureloop** [NEAT-project/neat#114]
There seems to be an issue on our network currently at abdn. SCTP/IPv6 works, but SCTP/IPv4 does not. NEAT HE incorrectly selects SCTP/IPv4 as transport, this leads to a broken connection. 

Reproduce: 

    examples/client_http_get -u /sample-1.html bsd10.nplab.de

On a network that does not have working SCTP/IPv4.

Output of neat debug log and tcpdump attached. 
[dump.txt](https://github.com/NEAT-project/neat/files/346576/dump.txt)
[client.txt](https://github.com/NEAT-project/neat/files/346577/client.txt)

**Comment by karlgrin** [comment]
@adventureloop some clarifications:
When you say that ipv4 is not working, what do you mean? Is it not configured with an ipv4 address or is it configured with an invalid ipv4 address? I find it strange that HE selects ipv4 since that implies a successful connection attempt and your log suggests otherwise.
PS. Will look into it as soon as I obtain ipv6. DS.

**Comment by tuexen** [comment]
@adventureloop 
Are you running FreeBSD 10.x or stable/10? There was a FreeBSD bug which resulted in all SCTP connections attempts (IPv4 or IPv6) to be reported successful. Therefore the HE will (correctly) choose the first SCTP candidate. From the dumpfile I see that IPv4 is tried first, so it will be chosen.
I fixed the bug in https://svnweb.freebsd.org/changeset/base/301000.
@karlgrin 
This doesn't look like a bug in the HE code. It was a kernel bug. But it shows one limitation of our HE implementation: We select the connection based on a successful connection setup and do not deal with the case that the actual connection doesn't work. This happened (and possibly still happens) for HTTP/TCP/IPv4 and HTTP/TCP/IPv6 where the IPv6 connection setup works but the data transfer doesn't due to MTU issues. Connection setup messages are not full sized frames whereas full sized frames are used during the data transfer (HTTP responses).

**Comment by karlgrin** [comment]
@tuexen thanks for your insight. Then we should close this issue and create a new one that specifically targets the case with successful connection setup but unusable connection.
@adventureloop I put this issue on hold until we are clear that this is indeed a HE issue.

**Comment by tuexen** [comment]
@karlgrin 
I agree, once we get a confirmation of my assumption, we should close this issue. How to deal with unusable connections is a different issue, it is not clear to me how to handle that (it might depend on the upper layer, using (D)TLS might help here). We can track that in an issue or consider it a research question. What do you think?

**Comment by adventureloop** [comment]
@tuexen Not 10 stable, but a current build from before your patches. 

I will close this issue. I have seen other issues with HE choices, but I need to figure out a minimal example case.

**Comment by karlgrin** [comment]
@tuexen I think we could issue it as a new issue and thus keep it in mind.

**Comment by tuexen** [comment]
@karlgrin Done: [Issue 126](https://github.com/NEAT-project/neat/issues/126)
@adventureloop Let me know if you find any issues with a current version including that patch.
