### ISSUE TITLE
Connection Results from HE to PM

### ISSUE THREAD

**Issue by karlgrin** [NEAT-project/neat#180]
Have started implementing the feedback of the connection attempts by HE to PM in branch karlgrin/he_pm_161107 . The question is if this is an ok start and thus could be merged into master. @bozakov could you check if the results from HE are correctly stored by the PM daemon; to me it looks ok.

**Comment by oystedal** [comment]
Two remarks:

The `neat_json_send_once` function was created for this very purpose, sending one-shot data to the PM and not really care too much about errors. I'd rather suggest we use that one instead of duplicating most of the neat_pm_socket code.

`json_pack` is able to create nested objects and arrays, e.g. `json_pack("[{s{si}}]", "my_object", "my_integer", 4);`. Thus, building the JSON object can be done in a quite compact manner. This should also make memory management simpler.

**Comment by karlgrin** [comment]
@oystedal I will indeed fix the creation of the JSON object. As regards, the neat_json_send_once, I am inclined to disagree with you. I think we should aim for a solution that does not generate unwarranted errors.

**Comment by bozakov** [comment]
@karlgrin The cached result is being sent back over the `neat_pm_socket`. It should be returned over the new `neat_cib_socket` instead, which was recently pushed to the master branch. Otherwise it looks like a good start. 

We also need an UID attribute for each CIB entry: the question is wether this should be generated by HE, or the PM. I can add it through the PM for now, but we need to think about a good way to invalidate/update existing entries (e.g. if network conditions have changed). We can discuss further on Slack if you like.

Another question: will HE always return a JSON list of CIB entries? (I need to update the PM side accordingly)

**Comment by karlgrin** [comment]
@bozakov I will definitely send the result over the neat_cib_socket. I am not sure I understand the need for a UID, could you please explain that (we could take it over Slack if you would prefer that). As regards HE and what it returns, as it is currently implemented, it will always return a JSON list of CIB entries. I am not sure I understand what else should be returned from HE.

**Comment by karlgrin** [comment]
@bozakov Revised HE-PM communication so that it transmits over the neat_cib_socket. Maybe you could check that it works correctly (although a bit simplistic). Maybe we could have a discussion over Slack on how to continue. I must admit that I am currently quite puzzled about the way the PM works.
@oystedal I have substantially compressed the creation of the JSON object (1 line) and uses the neat_json_send_once.

**Comment by bozakov** [comment]
@karlgrin Merged the policy manager from the main branch into yours. Basic communication with HE seems to be working, apart from some small nits. The PM logic is not too complex - let's discuss on Slack.

**Comment by karlgrin** [comment]
@bozakov Ok. Let's continue on Slack.
