### ISSUE TITLE
Resolve 'localhost'

### ISSUE THREAD

**Issue by bagder** [NEAT-project/neat#283]
The resolver functionality in neat is not handling `localhost` the way a user would presume, making neat_open() to "localhost" not use 127.0.0.1 or ::1 as most would presume.

This could be fixed by A) parsing `/etc/hosts` or B) providing a hard-coded response for this specific host name.

**Comment by dreibh** [comment]
A. If neat_open() ignores /etc/hosts, it will also cause problems with user-configured hostnames in /etc/hosts.

**Comment by kristrev** [comment]
I will take a look at this during the hackathon.

**Comment by kristrev** [comment]
I have implemented and merged approach B) above. If "localhost" is passed to the resolver, the resolver will translate this to 127.0.0.1 or ::1, depending on the family of the source address. Since parsing /etc/hosts is not critical as of how, I opted for the easiest localhost-"solution".

Adding support for /etc/hosts should not be so hard and the structure used for localhost can be recycled. The steps needed are:

* In nt_resolve, replace strcmp(localhost) with a function that checks the hosts-file for the provided node.  The check should be done after the literal-check, unlike the order of operations today.
* Store adresses (if any) somewhere, for example add a new field/fields to neat_resolver_request + family.
* In nt_resolver_localhost_populate_results (which should be renamed), tmp_literal should be replaced by what is read from /etc/hosts. Check that the address family matches the source address, and the rest of the code can remain as it is today.
