### ISSUE TITLE
client_https_get and let's encrypt

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/neat#306]
Hey,

we are trying to request a website via `client_https_get` from a web with let's encrypt certificates - it doesn't work.

When requesting from other web servers, like our www.neat-project.org website, everything works fine.

We tested he `helloworld.letsencrypt.org` and a variety of additional sites.
Any suggestions?
Felix

@ddragana @mcmanus @bagder

**Comment by bagder** [comment]
The CA cert bundle is "hard code" into tls-trust.c and needs to be updated. Get the latest converted one from https://curl.haxx.se/docs/caextract.html

The more long-term solution is of course to have neat use the system CA bundle for those systems where it can find one at configure/cmake time, or make it possible to point to a file/directory at run-time.

**Comment by dreibh** [comment]
This is a duplicate of bug #225 .

**Comment by weinrank** [comment]
@bagder 
I've updated to the latest ca-bundle - see #307 - but this does not fix my problem.
Getting pages from websites using let's encrypt still fails.

**Comment by bagder** [comment]
Ok, then it sounds more like a regular bug somewhere. But I can't really figure out off the top of my head why Let's Encrypt certs would have specific problems...

**Comment by bagder** [comment]
Reading `neat_security.c` says we do a whole bunch of OpenSSL calls there without checking return code and no logging/printing of them so its not easy to figure out what the problem is.

The call to [SSL_do_handshake()](https://wiki.openssl.org/index.php/Manual:SSL_do_handshake(3)) in particular is weird. As if the socket is blocking, that's a blocking function call that we shouldn't do, and if it isn't blocking we don't read the return code and act accordingly...

**Comment by weinrank** [comment]
Okay, got it. Server Name Indication (SNI) support was missing, added by
4e15eba95606064daeea1e4fee3541333e85185b

So it wasn't a problem of let's encrypt ... thx @bagder 

And I agree that the tls code needs some improvements.

**Comment by weinrank** [comment]
Closed by #307
