### ISSUE TITLE
MPTCP support? 

### ISSUE THREAD

**Issue by MonsterTan** [NEAT-project/neat#332]
Neat is the smart choice of the transport layer protocol. Can I make an application use MPTCP? How to use neat to set up an application to use MPTCP?

**Comment by bagder** [comment]
Dup of #326

**Comment by MonsterTan** [comment]
Sorry, I don't understand what your meaning, can you explain me clearly?
https://github.com/bagder

**Comment by bagder** [comment]
This exact same question is already asked in the other issue.

**Comment by MonsterTan** [comment]
yes, But I still did not get the answer when I click the link that links to me again. 
https://github.com/bagder

**Comment by bagder** [comment]
There is no answer there. That's just the same question asked again.

**Comment by MonsterTan** [comment]
ok, Now our group want to development an application(may about video or live stream, actually I am not sure.),which use MPTCP protocol managed by NEAT. However,  We may get some problem(many errors occur). So did you have developed any example for NEAT? Can you show us any example? Thx!
https://github.com/bagder

**Comment by bagder** [comment]
I've referred you to the open issue #326 about MPTCP because this was the same question asked again. I did not respond to the #326 issue since I don't know the answer. You highlighting me many times doesn't make me know the answer more.

Now you're adding more questions about MPTCP in this **closed issue**, I would advice against that. If you want to clarify what more about the MPTCP the issue is about, then communicate in #326. If you want to discuss the issue or get some help and support on using NEAT for various matters, I would strongly urge you instead ask on the mailing list.

**Comment by MonsterTan** [comment]
Okay, thanks for your advices. I am sorry for bothering you.

**Comment by perhurt** [comment]
MPTCP is supported by NEAT in the same way as other in-kernel transports, e.g., like TCP. Currently, however, you need to run NEAT on a mptcp-enabled Linux kernel to be able to use MPTCP.

**Comment by naeemk** [comment]
Can we have a clear example of how this works starting from NEAT API
properties, to policy/profile files, on an MPTCP-enabled Linux kernel? any
sample code snippet/example?

**Comment by perhurt** [comment]
See #326 for an example
